---
- name: Clone and build TireFire
  become: true
  become_method: sudo
  block:
    - name: Clone TireFire repository
      git:
        repo: 'https://github.com/CoolHandSquid/TireFire.git'
        dest: '/opt/TireFire'
        clone: yes
        update: yes

    - name: Execute build script
      command: ./Build.sh
      args:
        chdir: '/opt/TireFire'

- name: Clone and build Ares
  become: true
  block:
    - name: Clone Ares repository
      git:
        repo: 'https://github.com/bee-san/Ares.git'
        dest: '/opt/Ares'
        clone: yes
        update: yes

    - name: Execute build script
      command: docker build .
      args:
        chdir: '/opt/Ares'

