---
- name: Install genymotion
  block:
    - name: "Download genymotion"
      get_url:
        url: "https://dl.genymotion.com/releases/genymotion-3.6.0/genymotion-3.6.0-linux_x64.bin"
        dest: "/opt/genymotion-3.6.0-linux_x64.bin"
        mode: 0755
      become: true
      become_method: sudo

    - name: "Install genymotion"
      shell: /opt/genymotion-3.6.0-linux_x64.bin -d /opt/genymotion
      args:
        creates: /opt/genymotion/genymotion
      become: true
      become_method: sudo

- name: Install Frida
  pip:
    name: frida-tools
    state: latest

- name: Install Apt packages
  package:
    name: 
    - adb
    - virtualbox
    state: latest
  become: true
  become_method: sudo

- name: Install apktool
  block:
    - name: "Download apktool"
      get_url:
        url: "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
        dest: "/usr/local/bin/apktool"
        mode: 0755
      become: true
      become_method: sudo

    - name: "Install apktool"
      get_url:
        url: "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar"
        dest: "/usr/local/bin/apktool.jar"
        mode: 0755
      become: true
      become_method: sudo