---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: latest
  loop:
    - { name: 'impacket', source: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', source: 'git+https://github.com/Pennyw0rth/NetExec' }
    - { name: 'certipy-ad', source: 'git+https://github.com/ly4k/Certipy.git' }
