---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-browser"
    # - role: "roles/configure-logging"
    - role: gantsign.visual-studio-code
    - role: "roles/configure-system"
    - role: "roles/customize-terminal"
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
  post_tasks:
  - name: "Restart lightdm"
    become: true
    become_method: sudo
    service:
      name: lightdm
      state: restarted

