---
- name: Check msfdb status
  ignore_errors: yes
  ansible.builtin.command: msfdb status
  register: msfdb_status
  changed_when: false
  become: true
  become_method: sudo

- name: Initialize msfdb
  ignore_errors: yes
  ansible.builtin.command: msfdb init
  become: true
  become_method: sudo
  when: "'No configuration file found' in msfdb_status.stdout"